apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ca
  namespace: prelivegov-net
  annotations:
    fluxcd.io/automated: "false"

spec:
  interval: 1m
  releaseName: ca

  chart:
    spec:
      interval: 1m
      sourceRef:
        kind: GitRepository
        name: flux-prod
        namespace: flux-prod
      chart: platforms/hyperledger-fabric/charts/fabric-ca-server

  values:
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
                - key: eks.amazonaws.com/capacityType
                  operator: In
                  values:
                    - ON_DEMAND

    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "300m"
        memory: "256Mi"


    storage:
      enabled: false
      size: 512Mi
      createStorageClass: false
      storageClass: gp2

    global:
      serviceAccountName: vault-auth
      cluster:
        provider: aws
        cloudNativeServices: false
        kubernetesUrl: https://85CE266964E8B1DB527EB8913F2615B3.gr7.ap-southeast-1.eks.amazonaws.com
      vault:
        type: hashicorp
        network: fabric
        address: http://vault.vault.svc:8200
        authPath: prodprelivegov
        secretEngine: secretsv2
        secretPrefix: "data/prodprelivegov"
        role: vault-role
        tls: false
      proxy:
        provider: haproxy
        externalUrlSuffix: org4proxy.hlf.doconchain.com

    image:
      alpineUtils: ghcr.io/hyperledger/bevel-alpine:latest
      ca: ghcr.io/hyperledger/bevel-fabric-ca:latest
      pullSecret: ""

    server:
      removeCertsOnDelete: true
      tlsStatus: true
      adminUsername: prelivegov-admin
      adminPassword: prelivegov-adminpw
      subject: /C=US/ST=Massachusetts/L=Boston/O=PLGov
      clusterIpPort: 7054

    labels:
      service:
        - example1: example2
      pvc:
      deployment:
